### ISSUE TITLE
Bot seems to randomly crash after changing gamemodes while playing Adrenaline Gamer

### ISSUE THREAD

**Issue by thisisdark** [nekonomicon/Parabot#1]
I have no idea what causes it, but it seems to happen a lot more often when using commands such as "ffa" and tdm to change the gamemode, and it may also be caused by the amount of bots I am uisng. have attached the engine.log with the stack trace.

[engine.log](https://github.com/nekonomicon/Parabot/files/1020681/engine.txt)

Device: Verizon Samung Galaxy S7 running android 7.0

**Comment by nekonomicon** [comment]
Check new release: https://github.com/nekonomicon/Parabot/releases/tag/0.92.1
