### ISSUE TITLE
repository maintainence

### ISSUE THREAD

**Issue by ghost** [nekonomicon/Parabot#11]
Hello.

Please, help to setup bots on server)

After `git clone` and running `make` in `dlls` directory

```sh
/dlls$ make
g++ -m32 -O2 -pipe -DNDEBUG -fPIC -fno-rtti -I. -I../bot -I../utils -I../common -I../dlls -I../engine -I../pm_shared -I../metamod -c ../bot/bot.cpp -o ../bot/bot.o
In file included from /usr/include/c++/10/stdlib.h:36,
                 from ./extdll.h:55,
                 from ../bot/bot.cpp:9:
/usr/include/c++/10/cstdlib:41:10: fatal error: bits/c++config.h: No such file or directory
   41 | #include <bits/c++config.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:140: ../bot/bot.o] Error 1
```

There is no `bits` directory at the project root.

Another problem - at `release` repo section archive with precompiled binaries does not contain Parabot config.

**Comment by ushakov-31293** [comment]
As I understand now, release section zip archive is complete distribution unit.

But, after bot deploy I get

```
FATAL ERROR (shutting down): PF_MessageBegin_I: Invalid message: Cannot use broadcast message with a target entity
```

after a minute of game.

**Comment by ushakov-31293** [comment]
In OpposingForce case

```
L 03/17/2022 - 12:20:40: Log file started (file "logs/L0317047.log") (game "gearbox") (version "48/1.1.2.2/Stdio/8684")
Server IP address 192.168.1.2:27017
Host_Error: Couldn't get DLL API from 




,
 ,!
L 03/17/2022 - 12:20:40: FATAL ERROR (shutting down): Host_Error: Couldn't get DLL API from 




,
 ,!

FATAL ERROR (shutting down): Host_Error: Couldn't get DLL API from 




,
 ,!

```

**Comment by nekonomicon** [comment]
> There is no bits directory at the project root.

It's part of C++ runtime.
Try to compile with  `CXX=-std=gnu++98`
Or show output:
`c++ -v`

> Another problem - at release repo section archive with precompiled binaries does not contain Parabot config.

Bot library will create bot config on first run.

**Comment by ghost** [comment]
@nekonomicon 

1.

```
../bot/pb_weapon.cpp:77:1: error: narrowing conversion of ‘0.0’ from ‘double’ to ‘bool’ [-Wnarrowing]
```

Shall I add something like `-Wno-narrowing`?

2.
updated Makefile in dlls, excerpt
``` 
CXX ?=          g++ -std=gnu++98
```

is it right change?

**Comment by ghost** [comment]
@nekonomicon 

I can get fresh hlds, replace linux game dll in `liblist.gam`, run server, and config will be generated automatically?

Can we get performance boost by self-compilation with flags like `-march=native`?

And, big thanks for your reply)

**Comment by nekonomicon** [comment]
> Shall I add something like -Wno-narrowing?

Yep.


> updated Makefile in dlls, excerpt

> CXX ?= g++ -std=gnu++98 

> is it right change?

Oh, I forgot... Need to change CPPFLAGS variable, not CXX.
And you do not need to edit Makefile.
You can just type:
`$ make CPPFLAGS="-std=gnu++98"`

> I can get fresh hlds, replace linux game dll in liblist.gam, run server, and config will be generated automatically?

Yep.

> Can we get performance boost by self-compilation with flags like -march=native?

Yep, and it may be more efficient with AGGR_OPT and LTO flags.

**Comment by ghost** [comment]
@nekonomicon 

So,

```sh
make CPPFLAGS="-std=gnu++98" PB_64BI="true" AGGR_OPT LTO="true" NO_EXCEPTIONS="true"
```

 will be valid build command?

Debian `binutils` package will contain `gold` linker? It's from GCC toolchain, or clang?

If `hlds` is 32 bit, can it deal with 64bit parabot library?

**Comment by nekonomicon** [comment]
> will be valid build command?

Nope.

> Debian binutils package will contain gold linker?

No idea.

> It's from GCC toolchain, or clang?

`gold` is llvm's linker and gcc has backend for llvm.
Currently, you can use LTO with other linkers like `bfd` or `lld`

> If hlds is 32 bit, can it deal with 64bit parabot library?

Nope.
You can try to use 64-bit rehlds or xash3d with 64-bit server library from hlsdk-xash3d if you need.

**Comment by ghost** [comment]
@nekonomicon 

![screen](https://user-images.githubusercontent.com/73037194/159151850-3ad442f8-57d2-40f1-8088-2b6bd29d305e.png)

No config files created.

Tested on Deathmatch Classic, steam hlds.

I've copied config from hl, rename internal addons/valve directory to addons/dmc. Bots spawns, but interact with each other at minimum level. And, there is a bug - player could not move after spawn.

But on ModDB there is a comment that bot's should work ok on DMC.

**Comment by nekonomicon** [comment]
>  No config files created.

Check write permissions.

> And, there is a bug - player could not move after spawn.

Under hlds?

I'm not sure about GoldSource, but under Xash3D was bug with player hulls.

**Comment by ghost** [comment]
Current user write permissions?

**Comment by nekonomicon** [comment]
Permissions for directory `dmc/addons/parabot`.
